[package]
name = "addpath"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.0"
walkdir = "2.3"
dirs = "3.0"
rayon = "1.10"
crossterm = "0.27"
colored = "2.0"